Работа с БД
ztzmtv/PlaylistMaker pull request #23
Opened 2023-07-17 18:23 UTC by ztzmtv

ДЗ готово

2023-07-21 16:25 UTC, DmitrijEgorow commented on app/src/main/java/com/azmetov/playlistmaker/features/search/ui/fragment/SearchFragment.kt
Видимо, слева должна была быть лупа, а справа крестик

Нижняя панель навигации не скрывается под клавиатурой
![Screenshot_20230721_183702](https://github.com/ztzmtv/PlaylistMaker/assets/36837067/c7133d49-d62f-4c38-a032-710039e27756)

2023-07-21 16:25 UTC, DmitrijEgorow commented on app/src/main/java/com/azmetov/playlistmaker/features/media/ui/fragments/FavoritesFragment.kt
> +                    viewModel.favoritesList().collect { favorites ->
Нужно перенести часть логики в view model и сохранять в LiveData

2023-07-21 16:25 UTC, DmitrijEgorow commented on app/src/main/java/com/azmetov/playlistmaker/features/media/ui/fragments/FavoritesFragment.kt
>              spaceBottomDp = 16
Лучше такие магические числа выносить в именованные переменные или константы. Их можно будет переиспользовать в коде. На эту тему можно почитать, например, [эту статью](https://ru.hexlet.io/blog/posts/magic-numbers)

2023-07-23 12:39 UTC, ztzmtv commented
Я всё сделал, за исключением замечания с LiveData. Если честно, не понял, зачем так делать, фактически один Observable в другой переделывать.

2023-07-26 10:26 UTC, DmitrijEgorow requested changes

2023-07-26 10:26 UTC, DmitrijEgorow commented on app/src/main/res/layout/fragment_search.xml
Нижняя панель навигации не скрывается за клавиатурой

![Screenshot_20230726_164003](https://github.com/ztzmtv/PlaylistMaker/assets/36837067/f71816ed-e1bd-470a-a19d-d1df4b92be36)

2023-07-26 10:26 UTC, DmitrijEgorow commented on app/src/main/java/com/azmetov/playlistmaker/features/media/ui/fragments/FavoritesFragment.kt
Список избранного не обновляется


https://github.com/ztzmtv/PlaylistMaker/assets/36837067/bf4e5596-99ee-414b-8e19-a3358b038658

2023-07-26 10:26 UTC, DmitrijEgorow commented on app/src/main/java/com/azmetov/playlistmaker/features/media/ui/viewmodel/FavoritesViewModel.kt
> +                value = getFavoritesUseCase.getFavoritesUseCase()
На самом деле, из-за такого способа теперь не происходит обновление списка
Методы use case, предназначенные для получения списка избранных треков должны возвращать Flow, а обновление состояния UI экрана избранных треков должно происходить уже с использованием LiveData.

2023-07-26 10:36 UTC, DmitrijEgorow commented
Треки теперь сортируются по убыванию порядка добавления – здесь всё хорошо

2023-07-30 11:20 UTC, closed without merging